### PR TITLE
Rotary positional embeddings

### LINKED ISSUE #12: Add rotary position embeddings (RoPE)
Should be a very easy addition. Existing JAX code for the 1D version of it is available here:

https://blog.eleuther.ai/rotary-embeddings/

### PR DESCRIPTION
**Pull request by cfoster0**
Would close #12.

### CODE REVIEW

**Comment by cfoster0** [comment]
Right now, this includes the CLS token. Should probably exclude it from posembs.

**Comment by lucidrains** [comment]
Looks good! The only other thing is that sin and cos can be calculated once at the beginning, and passed to each attention module on forward

**Comment by cfoster0** [comment]
Ah right! Smart thinking.

**Comment by lucidrains** [comment]
Lgtm!

**Pull request merged**
